# Required connection configs for Kafka producer, consumer, and admin

#bootstrap.servers=<loaded from secrets vault>
#sasl.username=<loaded from secrets vault>
#sasl.password= <loaded from secrets vault>
#client.id=<loaded from secrets vault>

security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
group.id=news_ai_summary_group
auto.offset.reset=latest
enable.auto.commit=False
session.timeout.ms=45000
# send heartbeat every 3s
heartbeat.interval.ms=3000
# 30s before consumer considered dead
# 5 mins max between polls
max.poll.interval.ms=300000
# Connection settings
socket.keepalive.enable=True
# wait 1s before reconnect
reconnect.backoff.ms=1000
# max 10s between reconnects
reconnect.backoff.max.ms=10000